# Limite de tamanho de arquivos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Credenciais Supabase
supabase.url=${SUPABASE_URL}
supabase.key=${SUPABASE_KEY}
supabase.bucket=documentos-assinados

# Credenciais Google Cloud
google.credentials.json=${GOOGLE_CREDENTIALS_JSON}